n=float(input("so von ban dau:"))
k=float(input("so thang gui:"))
t=float(input("Lai suat/thang:"))
m=float(n*(1+k*t))
print("Voi so tien ban dau",str(n)+", sau ",str(k)+"thang gui,lai suat",str(t)+"/thang")
print("Thi so tien nhan duoc cuoi ky la:",str(m))